[package]
name = "ppt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
to_vec="0.1.0"
indexmap = "2.6.0"
id-arena = "2.2.1"